sudo: false
dist: trusty
language: ruby
rvm:
- 2.3
- 2.4
- 2.5
bundler_args: "--without convenience"
addons:
  apt:
    sources:
    - sourceline: "deb http://repo.aptly.info/ squeeze main"
      key_url: https://www.aptly.info/pubkey.txt
    packages:
    - aptly
    - gnupg
